// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAuthItemGroups(t *testing.T) {
	t.Parallel()

	query := AuthItemGroups()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAuthItemGroupsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuthItemGroupsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AuthItemGroups().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuthItemGroupsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AuthItemGroupSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuthItemGroupsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AuthItemGroupExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AuthItemGroup exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AuthItemGroupExists to return true, but got false.")
	}
}

func testAuthItemGroupsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	authItemGroupFound, err := FindAuthItemGroup(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if authItemGroupFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAuthItemGroupsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AuthItemGroups().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAuthItemGroupsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AuthItemGroups().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAuthItemGroupsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	authItemGroupOne := &AuthItemGroup{}
	authItemGroupTwo := &AuthItemGroup{}
	if err = randomize.Struct(seed, authItemGroupOne, authItemGroupDBTypes, false, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}
	if err = randomize.Struct(seed, authItemGroupTwo, authItemGroupDBTypes, false, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = authItemGroupOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = authItemGroupTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AuthItemGroups().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAuthItemGroupsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	authItemGroupOne := &AuthItemGroup{}
	authItemGroupTwo := &AuthItemGroup{}
	if err = randomize.Struct(seed, authItemGroupOne, authItemGroupDBTypes, false, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}
	if err = randomize.Struct(seed, authItemGroupTwo, authItemGroupDBTypes, false, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = authItemGroupOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = authItemGroupTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func authItemGroupBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func authItemGroupAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AuthItemGroup) error {
	*o = AuthItemGroup{}
	return nil
}

func testAuthItemGroupsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AuthItemGroup{}
	o := &AuthItemGroup{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup object: %s", err)
	}

	AddAuthItemGroupHook(boil.BeforeInsertHook, authItemGroupBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	authItemGroupBeforeInsertHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.AfterInsertHook, authItemGroupAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	authItemGroupAfterInsertHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.AfterSelectHook, authItemGroupAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	authItemGroupAfterSelectHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.BeforeUpdateHook, authItemGroupBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	authItemGroupBeforeUpdateHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.AfterUpdateHook, authItemGroupAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	authItemGroupAfterUpdateHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.BeforeDeleteHook, authItemGroupBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	authItemGroupBeforeDeleteHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.AfterDeleteHook, authItemGroupAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	authItemGroupAfterDeleteHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.BeforeUpsertHook, authItemGroupBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	authItemGroupBeforeUpsertHooks = []AuthItemGroupHook{}

	AddAuthItemGroupHook(boil.AfterUpsertHook, authItemGroupAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	authItemGroupAfterUpsertHooks = []AuthItemGroupHook{}
}

func testAuthItemGroupsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAuthItemGroupsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(authItemGroupColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAuthItemGroupsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAuthItemGroupsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AuthItemGroupSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAuthItemGroupsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AuthItemGroups().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	authItemGroupDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_                    = bytes.MinRead
)

func testAuthItemGroupsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(authItemGroupPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(authItemGroupAllColumns) == len(authItemGroupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAuthItemGroupsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(authItemGroupAllColumns) == len(authItemGroupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AuthItemGroup{}
	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, authItemGroupDBTypes, true, authItemGroupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(authItemGroupAllColumns, authItemGroupPrimaryKeyColumns) {
		fields = authItemGroupAllColumns
	} else {
		fields = strmangle.SetComplement(
			authItemGroupAllColumns,
			authItemGroupPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AuthItemGroupSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAuthItemGroupsUpsert(t *testing.T) {
	t.Parallel()

	if len(authItemGroupAllColumns) == len(authItemGroupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLAuthItemGroupUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AuthItemGroup{}
	if err = randomize.Struct(seed, &o, authItemGroupDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AuthItemGroup: %s", err)
	}

	count, err := AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, authItemGroupDBTypes, false, authItemGroupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuthItemGroup struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AuthItemGroup: %s", err)
	}

	count, err = AuthItemGroups().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
