// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthItemGroups   string
	AuthItems        string
	AuthRules        string
	PostMeta         string
	Posts            string
	SchemaMigrations string
	Users            string
}{
	AuthItemGroups:   "auth_item_groups",
	AuthItems:        "auth_items",
	AuthRules:        "auth_rules",
	PostMeta:         "post_meta",
	Posts:            "posts",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
