// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AuthItemGroups", testAuthItemGroupsUpsert)

	t.Run("AuthItems", testAuthItemsUpsert)

	t.Run("AuthRules", testAuthRulesUpsert)

	t.Run("PostMeta", testPostMetaUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
